### ISSUE TITLE
Decide the scope of disabling while submitting

### ISSUE THREAD

**Issue by DovydasNavickas** [SimplrJS/simplr-forms#36]
Multiple sources of updates can occur while submit is in progress:
* Reset and Clear buttons
* Non-disabled fields

We should decide whether a general disabling mechanism should be in place or at least Reset and Clear buttons should be disabled.

/cc @MartynasZilinskas @GiedriusGrabauskas

**Comment by MartynasZilinskas** [comment]
If the form is _submitting_ fields and buttons like reset, clear, submit should be disabled. Because if any fields have changed while submitting, the response (for example some kind of error) after submitting will be expired.

**Comment by DovydasNavickas** [comment]
Yeah, my thoughts are the same. Submitting should reject all changes.

**Comment by DovydasNavickas** [comment]
Done: https://github.com/SimplrJS/simplr-forms/commit/a1edeef461efd4e6842c736ceb2d757fc0a69fcc
