### ISSUE TITLE
FieldsGroup implementation

### ISSUE THREAD

**Issue by MartynasZilinskas** [SimplrJS/simplr-forms#37]
- [x] FieldsGroup base
- [x] FormStore implementation 
- [x] FieldsGroup implementation in field
- [x] Identical FieldsGroups grouping to array in `formStore.ToObject()`

**Comment by DovydasNavickas** [comment]
Done: https://github.com/SimplrJS/simplr-forms/commit/14ead955db50be99db16772f7a2f6256896fc19f
