### ISSUE TITLE
Validate on submit

### ISSUE THREAD

**Issue by DovydasNavickas** [SimplrJS/simplr-forms#55]
On form being submitted, validation should be ran.
@MartynasZilinskas, you did the validation, is it implemented?

I found `TODO` reminding me about this:
https://github.com/SimplrJS/simplr-forms/blob/dev/packages/simplr-forms-dom/src/components/form.tsx#L30

**Comment by MartynasZilinskas** [comment]
`simplr-validation` package only calls `ValidateField` and `ValidateForm` methods from _FormStore_.  I think the fields should be touched before calling `this.props.onSubmit` callback, so when this callback will be executing, fields will be already touched. 

Should we implement something like `TouchAllFields` method in _FormStore_ ?

**Comment by DovydasNavickas** [comment]
Done: https://github.com/SimplrJS/simplr-forms/commit/d6312bf94070c1e7adfa9bc57c35ae2482a1a23d
