### ISSUE TITLE
Dom Number component issues

### ISSUE THREAD

**Issue by MartynasZilinskas** [SimplrJS/simplr-forms#61]
We still haven't figured out the proper way of modifier mechanism.
Thus Number field doesn't work as intended. For now, it will be left without modifier which restricts any not numeric or special characters (like minus or comma) usage in the field.

**Comment by DovydasNavickas** [comment]
Done: https://github.com/SimplrJS/simplr-forms/commit/aee6400fff5222faa4ef71362b4c757180825789
