### ISSUE TITLE
Initialization is a bit off

### ISSUE THREAD

**Issue by DovydasNavickas** [SimplrJS/simplr-forms#82]
With the newest update, the validation is being initialized like so:
```ts
import { SubscriberContainer } from "simplr-validation/subscribers";
SubscriberContainer.Initialize();
```

It is a small thing and functionally works well, but it is the first thing that someone wanting to use validation will see and I think it's a bit tricky.

What I propose to do is:
a. Create an initialization method and expose it via main import, like so:
```ts
import { InitializeValidation } from "simplr-validation";
InitializeValidation();
```

Naming is subject to discussion, but the idea of having a function to call in the main import seems to be the best here. Any more ideas on naming or different approach at all?

/cc @GiedriusGrabauskas @MartynasZilinskas

**Comment by MartynasZilinskas** [comment]
Sounds about right. If you need something to do with internal validation part, you can use the first example. But for casual using, I think that's a great idea and less confusing.

**Comment by DovydasNavickas** [comment]
Done: https://github.com/SimplrJS/simplr-forms/commit/c905ac21473b18ecc6282eeb7b28ad077c906eec
